### ISSUE TITLE
Compilation with different interpreters (Python.h)

### ISSUE THREAD

**Issue by SylvainCorlay** [mdboom/numpy-boost#3]
Thanks @mdboom , great library. I could use it to wrap some C++ template library I wrote with no issue. It just works. I even realized that I compiled my wrapper with the system's Python.h and was running with another interpreter installed on my system (some anaconda install) and it worked...

I was wondering what are your plans with numpy-boost? Do you have any plan to contribute it upstream (in boost)?

**Comment by mdboom** [comment]
I'd be surprised if the generated code works across different non-bugfix releases versions of Python (e.g. 2.6.x vs. 2.7.x), since Python doesn't guarantee ABI compatibility...  Were the two versions you had from the same series?

I don't really have plans to contribute it upstream.  It was something I was using for a while, but haven't really had the opportunity to use it much lately.

**Comment by ddemidov** [comment]
> Thanks @mdboom , great library.

+1, I am using the library for all of my C++ to python integration projects. Would love to see it as part of Boost.Python!

**Comment by SylvainCorlay** [comment]
> I'd be surprised if the generated code works across different non-bugfix releases versions of Python (e.g. 2.6.x vs. 2.7.x), since Python doesn't guarantee ABI compatibility... Were the two versions you had from the same series?

These were different flavors of 2.7.x. Although I was surprised that it worked when I saw my mistake.
